### ISSUE TITLE
Does DRKG contain ICD code?

### ISSUE THREAD

**Issue by HarrialX** [gnn4dr/DRKG#22]
Hi Dear Author,

I see DRKG synthesizes a lot of knowledge bases together to get a very big graph, but does any of these knowledge bases contain ICD code for their diseases? If not, is there any way to map their disease codes to ICD? 

Thanks!

**Comment by mufeili** [comment]
The disease entities are associated with a MESH ID. I'm not sure if there are tools for mapping MESH IDs to ICD codes.
